plugins {
    id('application')
}

application {
    mainClass = 'com.geoffdoesstuff.java.MainDemoApp'
}

run {
    standardInput = System.in
}

dependencies {
    implementation(project(':utilities:library'))

    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.launcher)
}

test {
    useJUnitPlatform()
}
